name: grizzly_linalg
description: Linear algebra
version: 0.1.1-dev
homepage: https://github.com/Grizzly-dart/grizzly_linalg
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_array: ^0.2.2

dev_dependencies:
  test: ^0.12.0

dependency_overrides:
  grizzly_array:
    path: ../grizzly_array
  grizzly_primitives:
    path: ../grizzly_primitives