name: grizzly_linalg
description: Linear algebra
version: 0.0.1-dev
homepage: https://github.com/Grizzly-dart/grizzly_linalg
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_series: ^0.0.10-dev

dev_dependencies:
  test: ^0.12.0
