name: grizzly_linalg
description: Linear algebra
version: 1.0.0
homepage: https://github.com/Grizzly-dart/grizzly_linalg
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  grizzly:
    path: ../grizzly

dev_dependencies:
  test: ^1.21.6