name: grizzly_linalg
description: Linear algebra
version: 0.4.2
homepage: https://github.com/Grizzly-dart/grizzly_linalg
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_array: ^0.4.5

dev_dependencies:
  test: ^0.12.0

dev_dependency_overrides:
  grizzly_array:
    path: ../grizzly_array
  grizzly_primitives:
    path: ../grizzly_primitives